# Create tracking url
POST https://access-tracker-nwu7rw5hea-an.a.run.app/u
Content-Type: application/x-www-form-urlencoded

redirect=https://example.com

###
# show historis
GET https://access-tracker-nwu7rw5hea-an.a.run.app/u?id=[id]&key=[key]


###
# tracing
GET https://access-tracker-nwu7rw5hea-an.a.run.app/[id]/

###
# delete tracking
DELETE https://access-tracker-nwu7rw5hea-an.a.run.app/u?id=[id]&key=[key]


