name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  go:
    name: go test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      datastore:
        image: singularities/datastore-emulator
        env:
          DATASTORE_LISTEN_ADDRESS: 0.0.0.0:18001
          DATASTORE_PROJECT_ID: access-tracker-test
        ports:
          - 18001:18001
    env:
      DATASTORE_EMULATOR_HOST: localhost:18001
      DATASTORE_PROJECT_ID: access-tracker-test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./... -v -coverpkg=./... -race -coverprofile=coverage.out -covermode=atomic
    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
    
